package commoble.ccritter.client.model;

//Date: 6/30/2015 7:38:17 PM
//Template version 1.1
//Java generated by Techne
//Keep in mind that you still need to fill in some blanks
//- ZeuX


import org.lwjgl.opengl.GL11;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;

public class ModelChthon extends ModelBase
{
	//fields
	ModelRenderer head;
	ModelRenderer body;
	ModelRenderer righthorn;
	ModelRenderer lefthorn;
	ModelRenderer uppercross;
	ModelRenderer lowercross;
	
	public ModelChthon()
	{
		textureWidth = 64;
		textureHeight = 32;
	 
		head = new ModelRenderer(this, 0, 0);
		head.addBox(-4F, -8F, -4F, 8, 8, 8);
		head.setRotationPoint(0F, 14F, 0F);
		head.setTextureSize(64, 32);
		head.mirror = true;
		setRotation(head, 0F, 0F, 0F);
		body = new ModelRenderer(this, 16, 16);
		body.addBox(-2F, 0F, -2F, 4, 10, 4);
		body.setRotationPoint(0F, 14F, 0F);
		body.setTextureSize(64, 32);
		body.mirror = true;
		setRotation(body, 0F, 0F, 0F);
		righthorn = new ModelRenderer(this, 40, 16);
		righthorn.addBox(-7F, -10F, -2F, 4, 12, 4);
		righthorn.setRotationPoint(0F, 10F, 0F);
		righthorn.setTextureSize(64, 32);
		righthorn.mirror = true;
		setRotation(righthorn, 0F, 0F, 0F);
		lefthorn = new ModelRenderer(this, 40, 16);
		lefthorn.addBox(3F, -10F, -2F, 4, 12, 4);
		lefthorn.setRotationPoint(0F, 10F, 0F);
		lefthorn.setTextureSize(64, 32);
		lefthorn.mirror = true;
		setRotation(lefthorn, 0F, 0F, 0F);
		uppercross = new ModelRenderer(this, 33, 0);
		uppercross.addBox(-6F, 0F, -1F, 12, 2, 2);
		uppercross.setRotationPoint(0F, 16F, 0F);
		uppercross.setTextureSize(64, 32);
		uppercross.mirror = true;
		setRotation(uppercross, 0F, 0F, 0F);
		lowercross = new ModelRenderer(this, 33, 6);
		lowercross.addBox(-5F, 0F, -1F, 10, 2, 2);
		lowercross.setRotationPoint(0F, 19F, 0F);
		lowercross.setTextureSize(64, 32);
		lowercross.mirror = true;
		setRotation(lowercross, 0F, 0F, 0F);
	}
	
	public void render(float scale)
	{
		//super.render(entity, f, f1, f2, f3, f4, f5);
		//setRotationAngles(f, f1, f2, f3, f4, f5);
		//GL11.glEnable(GL11.GL_BLEND);
		//GL11.glBlendFunc(GL11.GL_ONE_MINUS_DST_COLOR, GL11.GL_ONE_MINUS_DST_COLOR);
		
		head.render(scale);
		body.render(scale);
		righthorn.render(scale);
		lefthorn.render(scale);
		uppercross.render(scale);
		lowercross.render(scale);
		
		// set the blend func back to normal just in case
		//GL11.glBlendFunc(GL11.GL_SRC_ALPHA, GL11.GL_ONE_MINUS_SRC_ALPHA);
		//GL11.glDisable(GL11.GL_BLEND);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

}
